
export const MEASUREMENT_FOR_TYPE_OF_CLOTHING_KEY_TO_VERBOSE: Record<
 string,
  string[]
> = {
  SHIRT: [
    "Tour de poitrine",
    "Tour de taille",
    "Longueur totale du vêtement",
    "Largeur d’épaules",
    "Tour de cou",
    "Longueur de dos (base du cou jusqu’à la taille)",
    "Longueur des manches (épaule jusqu’au poignet)",
    "Tour de bras (biceps)",
    "Tour de poignet",
    "Profondeur d’emmanchure (aisselle)",
    "Largeur de poitrine horizontale",
    "Longueur devant (du cou à la taille)",
    "Longueur épaule (de la base du cou à l’épaule)",
    "Hauteur épaule à épaule",
    "Hauteur d’emmanchure (pour manches ajustées)",
    "Pinces poitrine (pour ajustements)",
    "Pinces taille (pour ajustements)",
    "Pinces dos (pour ajustements)",
  ],
  PANTS: [
    "Tour de taille",
    "Tour de hanches",
    "Longueur totale du vêtement",
    "Entrejambe (pour pantalon, short)",
    "Hauteur entre taille et hanches",
    "Tour de cuisse",
    "Longueur de jupe (pour jupes, robes)",
    "Tour de bassin (pour certains vêtements féminins)",
    "Tour de ventre (pour morphologies spécifiques)",
    "Pinces taille (pour ajustements)",
  ],
  DRESS: [
    "Tour de poitrine / buste",
    "Tour de taille",
    "Tour de hanches",
    "Longueur totale du vêtement",
    "Largeur d’épaules",
    "Tour de cou",
    "Longueur de dos (base du cou jusqu’à la taille)",
    "Longueur des manches (épaule jusqu’au poignet)",
    "Tour de bras (biceps)",
    "Tour de poignet",
    "Entrejambe (pour pantalon, short)",
    "Hauteur entre taille et hanches",
    "Tour de cuisse",
    "Profondeur d’emmanchure (aisselle)",
    "Largeur de poitrine horizontale",
    "Longueur devant (du cou à la taille)",
    "Longueur épaule (de la base du cou à l’épaule)",
    "Hauteur épaule à épaule",
    "Tour de bassin (pour certains vêtements féminins)",
    "Hauteur poitrine à taille (pour pinces)",
    "Tour de ventre (pour morphologies spécifiques)",
    "Longueur de jupe (pour jupes, robes)",
    "Hauteur d’emmanchure (pour manches ajustées)",
    "Pinces poitrine (pour ajustements)",
    "Pinces taille (pour ajustements)",
    "Pinces dos (pour ajustements)",
  ],
};