/**
 * id du modals de serach des client de l'atelier
 */
export const CUSTOMER_WORKSHOP_SEARCH_MODAL = "CUSTOMER_SEARCH_MODAL";

/* id du modal du customer form */
export const CUSTOMER_WORKSHOP_FORM_MODAL = "CUSTOMER_WORKSHOP_FORM_MODAL";
export const ORDER_WORKSHOP_FORM_MODAL = "ORDER_WORKSHOP_MODAL";
export const CUSTOMER_WORKSHOP_DETAIL_ORDER_MODAL = "CUSTOMER_WORKSHOP_DETAIL_ORDER_MODAL"
export const WORKER_WORKSHOP_DETAIL_ORDER_MODAL = "WORKER_WORKSHOP_DETAIL_ORDER_MODAL"
export const ORDER_DETAIL_MODAL = "ORDER_DETAIL_MODAL"
export const LIST_ORDER_DETAIL_MODAL = "LIST_ORDER_DETAIL_MODAL"

export const HABERDASHERY_FORM_MODAL = "HABERDASHERY_FORM_MODAL"
export const MEET_FORM_MODAL = "MEET_FORM_MODAL"

export const WORKER_FORM_MODAL = "WORKER_FORM_MODAL"
export const LOGIN_FORM_MODAL = "LOGIN_FORM_MODAL"
export const REGISTER_FORM_MODAL = "REGISTER_FORM_MODAL"
export const USER_FORM_MODAL = "USER_FORM_MODAL"
export const WORKSHOP_FORM_MODAL = "WORKSHOP_FORM_MODAL"
